import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Munnar Experience - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">The Munnar Experience!</a>
        </h1>

        <p className={styles.description}>
          Nobody else knows Munnar better!
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href='/hotels-resorts'>
              <a>
                <h2>Hotels &amp; Resorts &rarr;</h2>
                <span>Explore the finest hotels to stay</span>
              </a>
            </Link> 
          </div>

          <div className={styles.card}>
            <Link href='/sightseeing-tours'>
              <a>
                <h2>Sightseeing Tours &rarr;</h2>
                <span>Find the finest hotels to stay</span>
              </a>
            </Link> 
          </div>

          <div className={styles.card}>
            <Link href='/boating'>
              <a>
                <h2>Boating &rarr;</h2>
                <span>Enjoy a boat ride in tranquility </span>
              </a>
            </Link> 
          </div>

          <div className={styles.card}>
            <Link href='/homestays'>
              <a>
                <h2>Homestays &rarr;</h2>
                <span>Live in a home away from home</span>
              </a>
            </Link> 
          </div>

          <div className={styles.card}>
            <Link href='/trekking'>
              <a>
                <h2>Trekking &rarr;</h2>
                <span>Explore the mystique hills of Munnar</span>
              </a>
            </Link> 
          </div>

          <div className={styles.card}>
            <Link href='/off-road-adventure'>
              <a>
                <h2>Off-road Adventure &rarr;</h2>
                <span>Explore the finest hotels to stay</span>
              </a>
            </Link> 
          </div>

          <div className={styles.card}>
            <Link href='/airport-pickupdrop'>
              <a>
                <h2>Airport Pickup/Drop &rarr;</h2>
                <span>Explore the mystique hills of Munnar</span>
              </a>
            </Link> 
          </div>

          <div className={styles.card}>
            <Link href='/hotels-resorts'>
              <a>
                <h2>Partner with us &rarr;</h2>
                <span>Explore the mystique hills of Munnar</span>
              </a>
            </Link> 
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          IceCrystal Designs
        </a>
      </footer>
    </div>
  )
}
